//auth api actions
export const LOGIN_USER = 'LOGIN_USER'
export const LOGOUT_USER = 'LOGOUT_USER'
export const CREATE_USER = 'CREATE_USER'
export const CHECK_UNIQ_ID = 'CHECK_UNIQ_ID'
export const REFRESH_TOKEN = 'REFRESH_TOKEN'
export const SET_REST_TOKENS = 'SET_REST_TOKENS'
export const CHANGE_PASSWORD = 'CHANGE_PASSWORD'
export const CHECK_CAPTCHA = 'CHECK_CAPTCHA'

//rest api actions
export const SEND_INVITE = 'SEND_INVITE'
export const FETCH_USERS = 'FETCH_USERS'
export const CONFIRM_USER = 'CONFIRM_USER'
export const DISABLE_USER = 'DISABLE_USER'
export const FETCH_NOTIFICATIONS = 'FETCH_NOTIFICATIONS'
export const FETCH_USERS_NOTIFICATIONS = 'FETCH_USERS_NOTIFICATIONS'
export const FETCH_EQUIPMENTS = 'FETCH_EQUIPMENTS'
export const FETCH_OBJECTS = 'FETCH_OBJECTS'
export const FETCH_AGGREGATORS = 'FETCH_AGGREGATORS'
export const GET_EVENT_DATES = 'GET_EVENT_DATES'
export const GET_CAPTCHA = 'GET_CAPTCHA'
export const GET_CHART_PARAMS = 'GET_CHART_PARAMS'
export const CHANGE_PROFILE_PASSWORD = 'CHANGE_PROFILE_PASSWORD'

//dictionaries
export const FETCH_USER_ROLES = 'FETCH_USER_ROLES'
export const FETCH_NOTIFY_TYPES = 'FETCH_NOTIFY_TYPES'
